### ISSUE TITLE
Add to LuaRocks

### ISSUE THREAD

**Issue by leafo** [kernelp4nic/moonbox#4]
Even though the project is not written in Lua it would be convenient to be able to install it from LuaRocks. A rockspec can install a regular script using `install = { bin = {...} }`

**Comment by kernelp4nic** [comment]
Great! It will be added to the site then.

**Comment by kernelp4nic** [comment]
Hello! I just added a rockspec to this repo and also uploaded to [moonscript rocks site](https://rocks.moonscript.org/modules/kernelp4nic/moonbox)

:)
